### ISSUE TITLE
[4pt]  - Display list of items on the Homepage - Student A

### ISSUE THREAD

**Issue by ReshyResh** [ReshyResh/Capstone-Javascript-APIs#15]
Create the main part of the homepage that keeps the layout from the wireframe: 

<img width="521" alt="Screenshot 2021-06-27 at 21 50 23" src="https://user-images.githubusercontent.com/7466903/123557585-f1afeb80-d791-11eb-96ae-17be082e9359.png">

When the page loads, the webapp retrieves data from  the selected API and shows the list of items on screen with the basic data (e.g. title + image).

Prepare also "Comments" and "Reservations" buttons. They should be doing nothing - just being displayed.

This task **does not** include displaying the number of likes for each item.

This task **does not** include the counter of the items.

**Comment by ShinobiWarior** [comment]
Hi Robert, 👋🏼 
Excellent work !!! 👏🏼 
However please consider some changes before continue:
  - Please fix the display logo issue. - The logo doesn't show up
  - Maybe you can try to use URLs and store images into bitcoin objects

Cheers!!! 🥂

**Comment by elyor-doniyorov** [comment]
Hello Robert! You did a great job 👍But you only need to style your app😎
