### ISSUE TITLE
First milestone

### ISSUE THREAD

**Issue by ReshyResh** [ReshyResh/Capstone-Javascript-APIs#21]
# Link to project
Click [here](https://github.com/ReshyResh/Capstone-Javascript-APIs/projects/1)
Number of members in the team: 3

**Comment by carlos-ssh** [comment]
Kindly assign the members for each activity:
- Each of the team members should assign themselves to the correct cards. Decide who will be the assignee for the cards marked as group tasks. All cards on your Kanban board should have assignees.

- You should see a circle with user's avatar on each card. See the example below:
<img width="372" alt="assigned_card" src="https://user-images.githubusercontent.com/22258274/132209558-b0b05a28-58a0-48eb-821f-148b2b14e441.png">

**Comment by ReshyResh** [comment]
# Changes
Assigned member to tasks.
Click [here](https://github.com/ReshyResh/Capstone-Javascript-APIs/projects/1)

**Comment by carlos-ssh** [comment]
Hi Team, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
